[build]
command = "pnpm run build"
functions = "netlify/functions"
publish = "build/client"

[functions]  # Correction de "fonctions" en "functions"
directory = "/apps/ai-weather-todo/.netlify/functions-internal"  # Correction de "fonctions-internal" en "functions-internal"

[dev]
command = "pnpm dev"
port = 3000

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"  # Ajout du "/" manquant avant ".netlify"
status = 200

[[headers]]
for = "/build/*"
[headers.values]
Cache-Control = "public, max-age=31536000, s-maxage=31536000"  # Suppression des guillemets autour de "Cache-Control"