[build]
command = "pnpm run build"
publish = "build"

[functions]
directory = "build"

[dev]
command = "pnpm dev"
port = 3000

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
