[build]
command = "pnpm build"
functions = "netlify/functions"
publish = "/apps/ai_weather_todo/build/client"

[fonctions]
directory = "/apps/ai_weather_todo/.netlify/fonctions-internal"

[dev]
command = "remix watch"
port = 3000

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, s-maxage=31536000"